language: python
python:
  - "2.7"
install:
  - curl -O https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.22.zip && unzip -q google_appengine_1.9.22.zip
  - pip install -r requirements-dev.txt
script: nosetests test/test_myria_down.py test/test_myria_up.py test_style.py -w appengine --with-gae --gae-lib-root=google_appengine
sudo: false
